language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

install:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != '7' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != '7' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi