language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - composer ci-test
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi